logging:
  level:
    com.github.j0rdanit0: trace

bot:
  token: ${CHATGPT_BOT_TOKEN}
  name: 'ChatGPT Bot'

open-ai:
  token: ${OPENAI_API_KEY}
  chat-model: 'gpt-3.5-turbo-0125'
#  chat-model: 'gpt-4-1106-preview'
  timeout: 30s

spring:
  threads:
    virtual:
      enabled: true